### ISSUE TITLE
DPI scaling issue

### ISSUE THREAD

**Issue by joszx** [cjAnteka/AntekaGearAnalyzer#1]
## Summary
Running a dual monitor setup with monitor 1 at 125% scale and monitor 2 at 100% scale, app spits out index out of bounds error for everything.

Might be a DPI scaling issue similar to https://stackoverflow.com/questions/40869982/dpi-scaling-level-affecting-win32gui-getwindowrect-in-python

### Screenshots
raw_screen_trimmed:
![raw_screen_trimmed](https://user-images.githubusercontent.com/24515765/168443175-e04f6951-6286-464d-a154-e87986370032.png)

stats:
![stats](https://user-images.githubusercontent.com/24515765/168443190-376e8e01-17f9-4493-8e57-a34d789a4f0f.png)

**Comment by cjAnteka** [comment]
Fixed in [6712634](https://github.com/cjAnteka/AntekaGearAnalyzer/commit/67126343c3a8eecc8d5b0d7d0730d6350a1ce211)

I pushed a new release as well.
